# Generated by Django 3.2.9 on 2021-11-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=31, verbose_name="Event creator's CSM username")),
                ('event_type', models.CharField(max_length=31, verbose_name='Nature of this event, from list. May be enum later.')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of event creation')),
                ('event_name', models.CharField(max_length=128, verbose_name='Event/incident name')),
            ],
        ),
        migrations.CreateModel(
            name='MapVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=31, verbose_name="Event creator's CSM username")),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of new version creation')),
                ('buffer_radius', models.IntegerField(verbose_name='Size in pixels of safety buffer zone')),
                ('is_airborne', models.BooleanField(verbose_name='Indicates airborne chemical threat.')),
                ('shape_toggles', models.BinaryField(max_length=15, verbose_name=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))),
                ('caption_text', models.CharField(max_length=1024)),
            ],
        ),
    ]
