# Generated by Django 3.2.9 on 2021-11-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_gen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapversion',
            name='shape_toggles',
        ),
        migrations.AddField(
            model_name='mapversion',
            name='parent_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map_gen.event'),
        ),
        migrations.AlterField(
            model_name='mapversion',
            name='buffer_radius',
            field=models.IntegerField(default=0, verbose_name='Size in pixels of safety buffer zone'),
        ),
        migrations.AlterField(
            model_name='mapversion',
            name='is_airborne',
            field=models.BooleanField(default=False, verbose_name='Indicates airborne chemical threat.'),
        ),
        migrations.CreateModel(
            name='Toggles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle', models.BooleanField(default=False)),
                ('dbNumber', models.IntegerField()),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_gen.mapversion')),
            ],
        ),
    ]
