# Generated by Django 3.2.9 on 2021-11-21 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_gen', '0002_auto_20211120_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toggles',
            name='dbNumber',
        ),
        migrations.AlterField(
            model_name='toggles',
            name='parent_map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map_gen.mapversion'),
        ),
    ]
