# Generated by Django 3.2.9 on 2021-11-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gen', '0003_auto_20211120_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='toggles',
            name='dbNumber',
            field=models.IntegerField(default=-1),
        ),
    ]
