# Generated by Django 3.2.9 on 2021-11-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gen', '0004_toggles_dbnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapversion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
