# Generated by Django 3.2.9 on 2021-11-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gen', '0005_mapversion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapversion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='map_gen/media/'),
        ),
    ]
