# Generated by Django 3.2.9 on 2021-11-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gen', '0006_alter_mapversion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapversion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mapversions'),
        ),
    ]
